name: Update LeetCode Stats

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update LeetCode Stats
    steps:
      - uses: actions/checkout@v3
      - uses: anuraghazra/leetcode-stats-readme@master
        with:
          LEETCODE_USERNAME: Isdre
